/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  testSidebar: [{type: 'autogenerated', dirName: 'test1'}],
  tutorialSidebar: [
    'intro',
      {
        'tutorial-basics': [{
          type: 'autogenerated',
          dirName: 'tutorial/tutorial-basics', // Generate sidebar slice from docs/tutorials/easy
        }]
      },
      {
        'tutorial-extras': [{
          type: 'autogenerated',
          dirName: 'tutorial/tutorial-extras', // Generate sidebar slice from docs/tutorials/hard
        }]
      },
  ],

};
