name: Deploy-Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - name: deploy to pages
        run: |
          GIT_USER=zhoulf1006 USE_SSH=true npm run deploy
